- name: run a webserver
  gather_facts: false
  hosts: all
  tasks:
  - name: install python3-apt
    ansible.builtin.raw: apt update && apt --fix-broken install -y && apt install -y python3-apt
  - name: install httpd
    ansible.builtin.apt:
      name: apache2
      update_cache: true
  - name: enable and start httpd service
    ansible.builtin.service:
      name: apache2
      enabled: true
      state: started
  - name: open firewall
    debug:
      msg: firewal
  - name: copy index.html
    ansible.builtin.copy:
      dest: "/var/www/html/index.html"
      content: |
        Hello World!