---
# Run with:
# ansible-playbook all variable.yaml -e 'variable=inventory_hostname'
- name: Show the value of any variable named on the command line
  hosts: all
  gather_facts: true

  tasks:
    - debug: var="{{ variable }}"
...
