---
all:
  children:
    webservers:
      hosts:
        Ubuntu:
          ansible_host: localhost
          ansible_port: 22
        Ubuntu-2:
          ansible_host: localhost
          ansible_port: 60222
        Ubuntu-3:
          ansible_host: localhost
          ansible_port: 60322
    local:
      hosts:
        localhost:
          ansible_connection: local
...
